services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./01-basegeografica.sql:/docker-entrypoint-initdb.d/01-basegeografica.sql
      - ./02-basegeografica.sql:/docker-entrypoint-initdb.d/02-basegeografica.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5441:5432"